lwm2m + fiware merge/create
diwise/integration-cip-havochvatten pull request #4
Opened 2023-02-23 10:15 UTC by nordbergmikael

2023-02-23 11:09 UTC, istyf requested changes
Jag har lämnat några kommentarer här och där.

2023-02-23 11:09 UTC, istyf commented on cmd/integration-cip-havochvatten/main.go
> +		logger.Fatal().Msg("select one endpont -endpoint=<iot or cip>")
endpont -> endpoint

2023-02-23 11:09 UTC, istyf commented on internal/application/cip/cip.go
> +			logger.Error().Err(err)
Funkar det där? Eller måste man ha ett Msg för att det skall flushas ut till loggen?

2023-02-23 11:09 UTC, istyf commented on internal/application/cip/cip.go
> +	id := fiware.WaterQualityObservedIDPrefix + temp.NutsCode
Vi skall inte köra med något :nuts: eller liknande här?

2023-02-23 11:09 UTC, istyf commented on internal/application/lwm2m/lwm2m.go
> +	ctx, span := tracer.Start(ctx, "integration-cip-havochvatten/lwm2m")
send-object eller något vore kanske ett bättre namn på ditt span. Här återanvänder du samma namn som tracern har.

2023-02-23 11:09 UTC, istyf commented on internal/application/lwm2m/lwm2m.go
> +	customTransport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
hmmm, nja, varför då?

2023-02-23 11:27 UTC, istyf commented on internal/application/lwm2m/lwm2m.go
> +	req.Header.Add("Content-Type", "application/json")
När jag funderat på det en stund, så tycker jag att vi kan använda application/senml+json som content type här. Se https://datatracker.ietf.org/doc/html/draft-jennings-core-senml-04#section-6

2023-02-23 12:09 UTC, nordbergmikael commented on internal/application/lwm2m/lwm2m.go
> +	req.Header.Add("Content-Type", "application/json")
ok

2023-02-23 12:10 UTC, nordbergmikael commented on internal/application/lwm2m/lwm2m.go
> +	customTransport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
gjort en möjlighet att slå av verifiering. Default är att den verifierar.

2023-02-24 08:14 UTC, istyf reviewed
Kom på några kommentarer till när jag fått sova på saken.

2023-02-24 08:14 UTC, istyf commented on cmd/integration-cip-havochvatten/main.go
> +		iotUrl := env.GetVariableOrDie(logger, "IOT_AGENT", "iot-agent URL")
Borde den här kanske hellre heta något i stil med LWM2M_ENDPOINT_URL? Den här tjänsten behöver/skall ju inte känna till att det är iot-agent som är mottagare.

2023-02-24 08:14 UTC, istyf commented on cmd/integration-cip-havochvatten/main.go
> +	cip "github.com/diwise/integration-cip-havochvatten/internal/application/cip"
This is a smell. Fixa cip.go i stället (se nedan).

2023-02-24 08:14 UTC, istyf commented on internal/application/cip/cip.go
> +package transform
Ser lite copy/paste ut? :) package cip tror jag skulle vara bättre.

2023-02-24 08:14 UTC, istyf commented on internal/application/lwm2m/lwm2m.go
> +		log.Error().Err(err).Msg("failed to send lwm2m object")
Behöver du logga här? Loggning sker även efter anropet till send med i princip samma info.

2023-02-24 14:32 UTC, istyf approved these changes
/lgtm

2023-02-24 14:33 UTC, merged